# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 62ff47415cc80936c6ef406d7dce5eed14b58fb59cc2d5db90bd0bcf842c44b93960a13514e0b1125558be7016d0b5957fa2f68f258aaf47074cc99ca44e179d

test:
  secret_key_base: 16230d434a7c71889b76d9e9f96acb8dbb2150fa985c0321df2289b1c75ceffa35821d1bbfd1bf476175174529ee6b88597e40d7362fcf673014886f6daa2106

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
